/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

CREATE TABLE `users` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(255) DEFAULT NULL,
  `email` varchar(255) DEFAULT NULL,
  `password` varchar(255) DEFAULT NULL,
  UNIQUE KEY `id` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO `users` (`id`, `name`, `email`, `password`) VALUES
(1, 'Jon Doe', 'ex@gmail.com', '$2y$10$56k/W7aMG.99pLu2OzIaE.R3i1Bp7ljMSzlCmTvzASMOxbPcoVbf6');
INSERT INTO `users` (`id`, `name`, `email`, `password`) VALUES
(2, 'Jon Doe', 'ex@gmail.com', '$2y$10$I0vDsXJ9S9g35wub.oHOS.4.Gg.t6.SMzSi6x3DpBkWnax2TFJNGW');
INSERT INTO `users` (`id`, `name`, `email`, `password`) VALUES
(3, 'Jon Doe', 'ex@gmail.com', '$2y$10$Tvj.1jDMzEn372Aa/L8yq.mrH23DjwEKhnVnm7kgNacUz0vvCiyH.');
INSERT INTO `users` (`id`, `name`, `email`, `password`) VALUES
(4, '', '', '$2y$10$hg3TGlYIta0C.qkDuP3qPe9QWhU8NBIOx8cmsyache4N6HFsuE.wO'),
(5, 'Mila', 'milabatanjski02@outlook.com', '$2y$10$iQoktY0/t6ioMZbeLlRe6u6uJ/mG0TaskjIh6KDRMDlYaROounJh.');

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;